name: PR Review Check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pr-review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Review Status
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.payload.repository.owner.login;
            const prAuthor = context.payload.pull_request.user.login;
            
            // If the PR author is the owner, automatically approve
            if (prAuthor === owner) {
              console.log('PR author is the repository owner - automatically approved');
              return;
            }
            
            // For non-owner PRs, check for owner's review
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            
            const ownerApproval = reviews.some(review => 
              review.user.login === owner && 
              review.state === 'APPROVED'
            );
            
            if (!ownerApproval) {
              core.setFailed('This PR requires approval from the repository owner before it can be merged.');
            }

permissions:
  pull-requests: read 